project1/encyclopedia/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.page, name="page"),
    path("wiki/", views.redirect, name="no_entry"),
    url(r'^search/$', views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("edit/", views.redirect, name="edit_no_entry"),
    path("random_page/", views.random_page, name="random_page")

]

project1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse

from . import util

import os
import random


def redirect(request):
    """
    Redirects links to index page, used when user attempts to acces an empty wiki or edit page

    request: HttpRequest object with information about user's request

    return: HttpResponseRedirect to index page
    """

    return HttpResponseRedirect("/")


def index(request):
    """
    Used for loading index page

    request: HttpRequest object with information about user's request

    return: render of index.html
    """

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries() # all encyclopedia entries for web page to load
    })


def page(request, entry):
    """
    Used to load specific encyclopedia entry pages

    request: HttpRequest object with information about user's request

    return: render of entry_page.html
    """

    found = True
    information = util.get_entry(entry)

    if information == None:
        found = False
        initial_entry = entry
        entry = "Not Found"
        information = "<h1>Entry \"" + initial_entry + "\" Does Not Exist </h1>"
        information += "<br>"

    return render(request, "encyclopedia/entry_page.html", {
        "entry": entry, # title of entry
        "information": information, # entry's content
        "found": found # bool whether entry was found or not
    })


def search(request):
    """
    Used to run search function of website

    request: HttpRequest object with information about user's request

    return: render of web page
    """

    query = request.GET.get("q")

    # if search query == name of an entry, then loads that entry's page
    if util.get_entry(query) != None:
            return page(request, query)
    else:
        sub_string_entries = []
        entries = util.list_entries()

        # checks if search query is substring in every entry name
        for entry in entries:
            if entry.find(query) >= 0:
                sub_string_entries.append(entry)

        return render(request, "encyclopedia/search.html", {
            "query": query, # search query
            "entries": sub_string_entries # entries list where query is substr
        })


def create(request):
    """
    Used to load Create New Page webpage

    request: HttpRequest object with information about user's request

    return: render of create.html, or redirect to newly created web page
    """

    title = request.GET.get("title")
    content = request.GET.get("content")
    information = util.get_entry(title)

    # if user entered a title
    if title != None:
        # if entry already exists
        if information != None:
            # alers user that entry already exists
            messages.error(request, "Page already exists")

            return render(request, "encyclopedia/create.html", {})
        else:
            # creates new entry page with user submitted information
            new_file = open( os.path.join("./entries" ,(str(title) + ".md")), "w")
            new_file.write("# " + str(title) + '\n')
            content = content.replace('\n','')
            new_file.write(content)
            new_file.close()

            return HttpResponseRedirect(('/wiki/' + str(title)))

    return render(request, "encyclopedia/create.html", {})


def edit(request, entry):
    """
    Used to load edit page for entries

    entry: title of entry user is requesting to edit

    request: HttpRequest object with information about user's request

    return: redirect to entry page, render of index page
    """

    content = request.GET.get("content")

    # if user submitted content for entry
    if content != None:
        # if entry alreqady exits, delete initial file
        try:
            os.remove(os.path.join("./entries" ,(str(entry) + ".md")))
        except:
            pass

        rewrite = open(os.path.join("./entries" ,(str(entry) + ".md")), "w")
        content = content.replace('\n','')
        rewrite.write(content)
        rewrite.close()

        return HttpResponseRedirect(('/wiki/' + str(entry)))
    else:
        open_file = open(os.path.join("./entries" ,(str(entry) + ".md")), "r")
        content = open_file.read()
        open_file.close()

        if content != None:
            return render(request, "encyclopedia/edit.html", {
                "entry": entry, # title of entry
                "content": content # content of entry
            })

    return render(request, "encyclopedia/index.html", {})

def random_page(request):
    """
    Used for Random Page feature of website

    request: HttpRequest object with information about user's request

    return: redirect to random encyclopedia entry
    """

    entries = util.list_entries()

    page_index = random.randint(0, (len(entries) - 1))
    title = entries[page_index]

    return HttpResponseRedirect(('/wiki/' + str(title)))

project1/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    {% if messages %}
                {% for message in messages %}
                <div class="main col-lg-10 col-md-9">
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
    {% endif %}
    <h1>Create New Encyclopedia Entry</h1>
    <br>
    <form id="create">
        <div>
            <h4 style="display: inline; vertical-align: middle;">Entry Title:</h4>
            <input style="vertical-align: middle;" type="text" name="title" placeholder="Title">
            <input style="vertical-align: middle;" type="submit" value="Create New Entry">
        </div>
        <br>
        <div>
            <textarea name="content" form="create" style="resize: none; height: auto;" placeholder="Entry Content" rows="30"></textarea>
        </div>
    </form>

{% endblock %}

project1/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{entry}}
{% endblock %}

{% block body %}
    <form id="edit">
        <div>
            <h4 style="vertical-align: middle;">Editing {{entry}}</h4>
            <a href= "{% url 'encyclopedia:edit' entry%}">
                <input style="vertical-align: middle;" type="submit" value="Save Entry">
            </a>
        </div>

        <br>
        
        <div>
            <textarea name="content" form="edit" style="resize: none; height: auto;" rows="30">{{content}}</textarea>
        </div>
    </form>
{% endblock %}

project1/encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
        {{ information|safe }}
        {% if not found %}
            <p style="vertical-align: top;">Please <a href="{% url 'encyclopedia:create' %}"> Create New Page </a> For This Entry</p>
        {% elif found %}
            <p>Click <a href="{% url 'encyclopedia:edit' entry%}">here</a> to edit this page</p>
        {% endif %}
{% endblock %}

project1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:page' entry %}">{{ entry }}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

project1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form role="search" action='/search/'>
                    <input name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for query in entries %}
            <li> <a href="{% url 'encyclopedia:page' query%}">{{ query }}</a> </li>
        {% empty %}
        <h3>No Entries Found for "{{ query }}"</h3>
        {% endfor %}
    </ul>

{% endblock %}